# pop()
names = {'anil','vijay','paresh','anita','purva','yogesh','sahil'}
print(names)
names.pop()
print(names)
names.pop()
print(names)
names.pop()
print(names)
names.pop()
print(names)
names.pop()
print(names)
names.pop()
print(names)
names.pop()
print(names)
del names
print(names)